### ISSUE TITLE
how to redirect to an application

### ISSUE THREAD

**Issue by dln949** [rxliuli/redirector#1]
When I click on a certain hyperlink on a web page within my web browser (Brave), I'd like to redirect it to launch an application installed on my Ubuntu Jammy system.  How do I do that?

**Comment by rxliuli** [comment]
What application? Can it be opened via URL schema? For example, you can enter vscode://settings/ in the browser to jump to vscode, an example rule is

`https://github.dev/*` => `vscode://vscode.git/clone?url=https://github.com{{pathname.input}}`

**Comment by dln949** [comment]
I'm trying to redirect to the flatpak application installed on my desktop computer called "Junction" - found here:  [https://flathub.org/apps/re.sonny.Junction](url) - which in the terminal executes with the command, 

/usr/bin/flatpak run re.sonny.Junction

I obviously do not know the correct way to set up the redirection part of the rule - or perhaps Redirector won't work for this?????

**Comment by rxliuli** [comment]
I found its API, and you can use it through the following URL Schema

```sh
x-junction://https://github.com
```

For example, if you want to open the Google website using Junction, you can configure rules

`(https://www.google.com/.*)` => `x-junction://$1`

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/26aaf7eb-2aed-40f4-991b-2c993213f4ef">

**Comment by dln949** [comment]
Sorry, but I've run into another issue that I *THINK* is related, but I'm not a tech type person, so perhaps you'll say this should be a new issue.  

I followed your suggestion above, using this rule within the Brave browser:  (https://*) >> x-junction://$1  But, when I click on an https:// hyperlink on a web page within the Brave browser, it opens Junction, but the URL supplied to Junction has  file:///home/main1 as the prefix, and after the https it is missing a : and a /.  (So, for example, if in the Brave browser I click on a hyperlink on a web page for https://google.com , what is supplied to Junction is   file:///home/main1/https/www.google.com instead of just https://google.com.  This obviously won't work, any browser I select within Junction to open the desired web site - https://google.com in this example - will instead attempt to open file://home/main1/https/google.com, which of course will fail.  On my Ubuntu system, /home/main1 is my user home directory.)  How do I make Redirector send the URL to Junction without the prefix of file:///home/main1 for my home directory, and how do I also make it have https:// in the correct URL instead of simply https/ ?

**Comment by rxliuli** [comment]
>  (https://*) >> x-junction://$1 

Use `(https://.*)` instead of `(https://*)`, note that there is an additional `.` in it.

**Comment by rxliuli** [comment]
What will happen if you click <x-junction://https://www.google.com/> directly in the browser? Can Junction be opened correctly?

**Comment by dln949** [comment]
With the Redirector rule of (https://.*)  => x-junction://$1 in effect, when I enter x-junction://https://www.google.com directly in the URL field of the Brave browser, Junction does open up as expected, but the URL it is receiving as shown within the Junction application is this erroneous URL:  /home/main1/https/search.brave.com/search?q=x-junction%3A%2F%2Fhttps%3A%2F%2Fwww.google.com&source=desktop .

**Comment by rxliuli** [comment]
It seems that directly opening the link has the same issue, it might be a problem with Chrome or Junction, maybe you can check https://github.com/sonnyp/Junction/issues/163.

**Comment by dln949** [comment]
Ok, thanks for pointing that out.
